// <auto-generated />
namespace CreativeCollab_UberDealership3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ridecardriver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ridecardriver));
        
        string IMigrationMetadata.Id
        {
            get { return "202308081443196_ride-car-driver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
